// Relative file path: ./app\threejs-fiber\layout.js

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function AboutLayout({ children }) {
  return (<>
            {children}
  </>
  );
}