// Relative file path: ./app\voronoi\layout.js



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AboutLayout({ children }) {
  return (<>
            {children}

  </>

  );
}